# DATA PREPROCESSING AND DATA CLEANING

In [2]:
# import the necessary libraries. 
import pandas as pd
import numpy as np

In [3]:
# Avoid unnessary warnings in this module(Ex: software updation, version-mismatch, cache errors)
import warnings
warnings.filterwarnings('ignore')

In [4]:
# Read the datasets
df=pd.read_csv('Parkinsons.csv')	
df.head()

,Symptom,Alzheimer_Disease,Parkinsons_Disease,Overlapping_Symptom
0,Memory loss,Yes,No,No
1,Confusion,Yes,No,No
2,Difficulty in thinking,Yes,No,No
3,Disorientation,Yes,No,No
4,Tremors,No,Yes,No

In [5]:
df.tail()

,Symptom,Alzheimer_Disease,Parkinsons_Disease,Overlapping_Symptom
21,Incontinence,Yes,Yes,No
22,Severe memory loss,Yes,No,No
23,Difficulty recognizing people,Yes,No,No
24,Visual-spatial difficulties,Yes,No,No
25,Rapid eye movement (REM) sleep disorder,No,Yes,No

In [6]:
# Check the dimension of our datasets (ex: how many rows and columns)
df.shape

(26, 4)

In [7]:
# Check the overall datasets value
df.size

104

In [8]:
# Check our data how many columns they are.
df.columns

Index(['Symptom', 'Alzheimer_Disease', 'Parkinsons_Disease',
       'Overlapping_Symptom'],
      dtype='object')

In [14]:
df['Parkinsons_Disease'].unique()

array(['No', 'Yes'], dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

var = ['Symptom', 'Alzheimer_Disease', 'Parkinsons_Disease',
       'Overlapping_Symptom']
  
for i in var:
    df[i] = le.fit_transform(df[i]).astype(int)

In [18]:
# Check our datasets information (ex: data_type, NUlL_count, Columns, and so on)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Symptom              26 non-null     int32
 1   Alzheimer_Disease    26 non-null     int32
 2   Parkinsons_Disease   26 non-null     int32
 3   Overlapping_Symptom  26 non-null     int32
dtypes: int32(4)
memory usage: 548.0 bytes

In [22]:
# Check if any null value in our datasets
df.isnull()

    Symptom  Alzheimer_Disease  Parkinsons_Disease  Overlapping_Symptom
0     False              False               False                False
1     False              False               False                False
2     False              False               False                False
3     False              False               False                False
4     False              False               False                False
5     False              False               False                False
6     False              False               False                False
7     False              False               False                False
8     False              False               False                False
9     False              False               False                False
10    False              False               False                False
11    False              False               False                False
12    False              False               False                False
13    False              False               False                False
14    False              False               False                False
15    False              False               False                False
16    False              False               False                False
17    False              False               False                False
18    False              False               False                False
19    False              False               False                False
20    False              False               False                False
21    False              False               False                False
22    False              False               False                False
23    False              False               False                False
24    False              False               False                False
25    False              False               False                False

In [20]:
df.isnull().sum()

Symptom                0
Alzheimer_Disease      0
Parkinsons_Disease     0
Overlapping_Symptom    0
dtype: int64

In [24]:
# Remove the null values
df = df.dropna()

In [26]:
# Check the unique value for specific columns
df['Parkinsons_Disease'].unique()

array([0, 1])

In [28]:
# Describe our data in stastical point of view.
df.describe()

         Symptom  Alzheimer_Disease  Parkinsons_Disease  Overlapping_Symptom
count  26.000000          26.000000           26.000000            26.000000
mean   12.500000           0.615385            0.730769             0.307692
std     7.648529           0.496139            0.452344             0.470679
min     0.000000           0.000000            0.000000             0.000000
25%     6.250000           0.000000            0.250000             0.000000
50%    12.500000           1.000000            1.000000             0.000000
75%    18.750000           1.000000            1.000000             1.000000
max    25.000000           1.000000            1.000000             1.000000

In [30]:
# Check the relationship between each individual columns.
df.corr()

,Symptom,Alzheimer_Disease,Parkinsons_Disease,Overlapping_Symptom
Symptom,1.000000,-0.189737,-0.028904,-0.233333
Alzheimer_Disease,-0.189737,1.000000,-0.479857,0.527046
Parkinsons_Disease,-0.028904,-0.479857,1.000000,0.404651
Overlapping_Symptom,-0.233333,0.527046,0.404651,1.000000

In [32]:
# Checkout the data is duplicated.
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
dtype: bool

In [34]:
# Total sum of duplicated values.
sum(df.duplicated())

0

In [36]:
pd.Categorical(df['Parkinsons_Disease']).describe()

            counts     freqs
categories
0                7  0.269231
1               19  0.730769